import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, BookOpen, Building2, CheckCircle2, ChevronRight, CircleHelp, Dna, Globe2, HeartPulse, Leaf, MapPin, Menu, Search, ShieldCheck, Sparkles, Store, Tag, UtensilsCrossed, X} from 'lucide-react';
import './styles.css';

const moods=['Comforting','Adventurous','Healthy','Indulgent','Quick','Celebratory'];
const cravings=['Spicy','Crispy','Creamy','Smoky','Sweet','Umami'];
const cuisines=['Andhra / Telangana','South Indian','North Indian','Middle Eastern','East Asian','Mediterranean','European','African','Latin American'];
const places=[
 {name:"Nani’s Kitchen",area:'Banjara Hills · 1.8 km',cuisine:'Andhra • Home-style',vibe:'Lowkey',rating:'4.6',time:'28–35 min',price:'₹₹',offers:['20% off','Free delivery'],moods:['Comforting','Spicy'],cravings:['Spicy','Umami'],platforms:['Zomato integration','Swiggy integration'],desc:'A quiet local favourite for punchy Andhra flavours and generous portions.',nutrition:['Protein-rich options','Fermented sides'],source:'Illustrative demo data — not live availability'},
 {name:'The Hidden Tiffin',area:'Himayatnagar · 2.4 km',cuisine:'South Indian • Tiffin',vibe:'Hidden gem',rating:'4.7',time:'22–30 min',price:'₹',offers:['₹125 off'],moods:['Quick','Comforting'],cravings:['Crispy','Umami'],platforms:['Swiggy integration'],desc:'A tiny spot for crisp dosa, podi and late-evening comfort.',nutrition:['Whole-grain choices','Legume sides'],source:'Illustrative demo data — not live availability'},
 {name:'Charcoal Stories',area:'Jubilee Hills · 3.1 km',cuisine:'Kebab • Grill',vibe:'Under the radar',rating:'4.5',time:'32–40 min',price:'₹₹₹',offers:['15% off'],moods:['Adventurous','Indulgent'],cravings:['Smoky','Spicy'],platforms:['Zomato integration','Swiggy integration'],desc:'Smoky grills, strong marinades and a menu built for sharing.',nutrition:['High-protein plates','Vegetable add-ons'],source:'Illustrative demo data — not live availability'},
 {name:'Mango & Millet',area:'Madhapur · 2.9 km',cuisine:'Healthy • Bowls',vibe:'Local find',rating:'4.4',time:'25–32 min',price:'₹₹',offers:['10% off'],moods:['Healthy','Quick'],cravings:['Creamy','Sweet'],platforms:['Swiggy integration'],desc:'Millet bowls and seasonal plates when you want lighter food without boring food.',nutrition:['Fibre-forward','Plant proteins'],source:'Illustrative demo data — not live availability'}
];
const nutrientDirectory=[
 {name:'Protein',group:'Macronutrient',role:'Amino-acid building blocks for tissues, enzymes and many biological functions.',sources:'Pulses, beans, dairy, eggs, fish, meat, soy, nuts and seeds.'},
 {name:'Dietary fibre',group:'Carbohydrate',role:'Supports normal bowel function and is associated with healthier dietary patterns.',sources:'Pulses, whole grains, vegetables, fruit, nuts and seeds.'},
 {name:'Iron',group:'Mineral',role:'Needed for haemoglobin and oxygen transport; absorption differs by food form and meal composition.',sources:'Meat and seafood; beans, lentils and fortified foods also contribute.'},
 {name:'Vitamin B12',group:'Vitamin',role:'Important for red blood cell formation and normal neurological function.',sources:'Naturally concentrated in animal foods; fortified foods can provide B12.'},
 {name:'Magnesium',group:'Mineral',role:'Involved in many enzymatic reactions and normal nerve and muscle function.',sources:'Nuts, seeds, legumes, whole grains and leafy vegetables.'},
 {name:'Omega-3 fats',group:'Fat',role:'Essential fatty acids with important structural and physiological roles.',sources:'Fatty fish; some plant foods provide ALA, including flax and chia.'},
 {name:'Vitamin C',group:'Vitamin',role:'Antioxidant nutrient involved in collagen formation and iron absorption.',sources:'Citrus, guava, peppers, berries, tomatoes and many vegetables.'},
 {name:'Potassium',group:'Mineral',role:'Essential electrolyte involved in fluid balance, nerve signalling and muscle contraction.',sources:'Beans, potatoes, leafy greens, fruit, dairy and many whole foods.'}
];
const scienceCards=[
 {title:'Turmeric × black pepper',claim:'Piperine can markedly increase curcumin exposure.',detail:'A 1998 human pharmacokinetic study reported a 2000% increase in curcumin bioavailability when 20 mg piperine was given with 2 g curcumin. This is a specific study dose/formulation result—not a promise that ordinary turmeric food always produces a 20× increase.',tag:'Human study',href:'https://pubmed.ncbi.nlm.nih.gov/9619120/'},
 {title:'What “bioavailable” means',claim:'Food composition is not the same as absorbed dose.',detail:'Crave Plate should separate nutrient content, estimated bioaccessibility/bioavailability evidence, and proven clinical outcomes. A compound can be present in a food without a predictable absorbed amount.',tag:'Evidence model',href:'https://pubmed.ncbi.nlm.nih.gov/17999464/'},
 {title:'Fats: not simply “good” or “bad”',claim:'Fat quality matters.',detail:'WHO distinguishes unsaturated fats from saturated and trans fats. Industrial trans fats should be avoided; saturated fat intake should be limited and replaced where practical with unsaturated fats.',tag:'WHO guidance',href:'https://www.who.int/news-room/fact-sheets/detail/healthy-diet'},
 {title:'Legumes belong in the conversation',claim:'Beans and pulses can contribute protein, fibre and minerals.',detail:'WHO identifies legumes as part of diverse healthy diets. Crave Plate should compare foods by serving size and nutrient density rather than using blanket “better than chicken” claims.',tag:'Whole-food science',href:'https://www.who.int/health-topics/healthy-diet'}
];

function App(){
 const [view,setView]=useState('discover');
 const [mood,setMood]=useState(''); const [crave,setCrave]=useState(''); const [query,setQuery]=useState(''); const [lowkey,setLowkey]=useState(true); const [cuisine,setCuisine]=useState(''); const [mobile,setMobile]=useState(false);
 const [partnerType,setPartnerType]=useState('Street vendor');
 const results=useMemo(()=>places.filter(p=>(!mood||p.moods.includes(mood))&&(!crave||p.cravings.includes(crave))&&(!cuisine||p.cuisine.toLowerCase().includes(cuisine.toLowerCase().split(' ')[0].toLowerCase()))&&(!query||(`${p.name} ${p.cuisine} ${p.area}`.toLowerCase().includes(query.toLowerCase())))&&(!lowkey||p.vibe!=='Local find')),[mood,crave,query,lowkey,cuisine]);
 const go=(v)=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="app">
  <header className="nav"><button className="brand" onClick={()=>go('discover')}><span className="brand-mark">CP</span><span>CRAVE PLATE</span></button><nav className={mobile?'nav-links open':'nav-links'}><button onClick={()=>go('discover')}>Discover</button><button onClick={()=>go('nutrition')}>Health Directory</button><button onClick={()=>go('science')}>Food Science</button><button onClick={()=>go('collab')}>Collaborate</button></nav><div className="nav-actions"><button className="location" type="button" aria-label="Launch city: Hyderabad"><MapPin size={16}/> Hyderabad <ChevronRight size={15}/></button><button className="menu-btn" type="button" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  {view==='discover'&&<>
   <section className="hero"><div className="orb orb1"></div><div className="orb orb2"></div><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> Hyderabad launch · built for the world</div><h1>Don't search for food. <em>Understand</em> your plate.</h1><p>Crave Plate translates mood, craving, budget, dietary preferences and nutrition curiosity into a shortlist of restaurants, street vendors and hidden food places—then shows how you can reach them.</p><div className="search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “spicy, comforting, under ₹300”…"/><button type="button" onClick={()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'})}>Find my plate</button></div><div className="trust"><span><span className="dot"></span> Partner availability is live only when connected</span><span>•</span><span>Lowkey discovery</span><span>•</span><span>Science-labelled nutrition</span></div></div><div className="hero-plate"><div className="plate-ring"><div className="dish"><div className="dish-center">CRAVE<br/><small>your plate</small></div><div className="garnish g1"></div><div className="garnish g2"></div><div className="garnish g3"></div></div></div><div className="floating-card fc1"><span>intent</span><b>{mood||'comfort + adventure'}</b></div><div className="floating-card fc2"><span>knowledge</span><b>taste + nutrition + access</b></div></div></section>
   <section className="selector" id="discover"><div className="section-head"><div><span className="kicker">01 / HUMAN INTENT</span><h2>Start with how you feel.</h2></div><span className="counter">{results.length} current matches</span></div><div className="chips">{moods.map(x=><button className={mood===x?'chip active':'chip'} onClick={()=>setMood(mood===x?'':x)} key={x}>{x}</button>)}</div><div className="section-head second"><div><span className="kicker">02 / CRAVING</span><h2>Make it deliciously specific.</h2></div></div><div className="chips">{cravings.map(x=><button className={crave===x?'chip active':'chip'} onClick={()=>setCrave(crave===x?'':x)} key={x}>{x}</button>)}</div><div className="section-head second"><div><span className="kicker">03 / WORLD CUISINE</span><h2>Choose a food culture—or let us surprise you.</h2></div></div><div className="chips">{cuisines.map(x=><button className={cuisine===x?'chip active':'chip'} onClick={()=>setCuisine(cuisine===x?'':x)} key={x}>{x}</button>)}</div><div className="filters"><button className={lowkey?'filter active':''} onClick={()=>setLowkey(!lowkey)}><Sparkles size={15}/> Surface lowkey / under-the-radar places</button><span className="hint">Every recommendation can expose the reason, source and confidence behind it.</span></div></section>
   <section className="results" id="results"><div className="results-top"><div><span className="kicker">04 / YOUR PLATE SHORTLIST</span><h2>Places that fit the feeling.</h2></div><button className="mapbtn"><MapPin size={16}/> Map view</button></div><div className="cards">{results.length===0?<div className="empty-state"><Sparkles size={18}/><h3>No exact matches yet.</h3><p>Try clearing one filter, changing the craving, or searching by cuisine. Crave Plate will only show live partner data when a permitted connection exists.</p></div>:results.map((p,i)=><article className="card" key={p.name}><div className="card-image"><div className={'food food'+i}></div><span className="badge">{p.vibe}</span></div><div className="card-body"><div className="meta"><span>{p.rating} ★</span><span>{p.time}</span><span>{p.price}</span></div><h3>{p.name}</h3><p className="cuisine">{p.cuisine} · {p.area}</p><p>{p.desc}</p><div className="why"><Sparkles size={14}/><span><b>Why it matches:</b> {mood||p.moods[0]} + {crave||p.cravings[0]}</span></div><div className="nutrition-tags">{p.nutrition.map(n=><span key={n}><Leaf size={12}/>{n}</span>)}</div><div className="offers">{p.offers.map(o=><span key={o}><Tag size={13}/>{o}</span>)}</div><div className="partners">{p.platforms.map(x=><button key={x} className="partner" type="button" disabled title="Partner integration placeholder">{x}<ArrowUpRight size={13}/></button>)}</div><small className="source">Data state: {p.source}</small></div></article>)}</div></section>
   <section className="compare"><div><span className="kicker">05 / ONE STOP, NOT ONE MORE TAB</span><h2>See the order path before you tap.</h2><p>Crave Plate is the decision layer. Partner adapters return permitted availability, ETA, fees and offers; the backend normalizes them into one comparison without putting partner credentials in the browser.</p><div className="callout"><ShieldCheck size={18}/><span><b>Trust rule:</b> no fabricated “live” availability. If the backend has not verified it, the UI says so.</span></div></div><div className="compare-panel"><div className="compare-row head"><span>Partner</span><span>ETA</span><span>Delivery</span><span>Offer</span></div><div className="compare-row"><b>Zomato</b><span>—</span><span>—</span><span>Connect API</span></div><div className="compare-row"><b>Swiggy</b><span>—</span><span>—</span><span>Connect API</span></div><div className="compare-row"><b>Future partner</b><span>—</span><span>—</span><span>Adapter ready</span></div><div className="compare-note">This starter UI intentionally separates design from partner authorization, commercial terms and live API responses.</div></div></section>
   <section className="departments"><div className="department-intro"><span className="kicker">06 / THE CRAVE PLATE ECOSYSTEM</span><h2>More than discovery.</h2><p>A consumer app on the surface; a food intelligence and collaboration platform underneath.</p></div><div className="department-grid"><button onClick={()=>go('nutrition')}><HeartPulse/><b>Health Directory</b><span>Nutrition, nutrients, food combinations, evidence and bioavailability explainers.</span></button><button onClick={()=>go('science')}><Dna/><b>Food Science Lab</b><span>Interactive evidence cards that explain what happens from bite → digestion → absorption.</span></button><button onClick={()=>go('collab')}><Building2/><b>Business Collaboration Wing</b><span>Open onboarding for street vendors, restaurants, brands, chefs and delivery partners.</span></button><button onClick={()=>go('discover')}><Globe2/><b>Global Cuisine Atlas</b><span>Explore cuisines, ingredients, preparation styles and cultural context.</span></button></div></section>
  </>}
  {view==='nutrition'&&<Nutrition/>}
  {view==='science'&&<Science/>}
  {view==='collab'&&<Collab partnerType={partnerType} setPartnerType={setPartnerType}/>} 
  <footer><div className="brand"><span className="brand-mark">CP</span><span>CRAVE PLATE</span></div><span>Decide less. Understand more. Crave better.</span><span>Hyderabad → World</span></footer>
 </div>
}
function Nutrition(){const [q,setQ]=useState('');const filtered=nutrientDirectory.filter(n=>(n.name+' '+n.group+' '+n.role+' '+n.sources).toLowerCase().includes(q.toLowerCase()));return <main className="directory"><section className="directory-hero"><span className="kicker">HEALTH DIRECTORY / PUBLIC KNOWLEDGE</span><h1>Know what is on your plate—and what science actually says.</h1><p>Crave Plate is designed to explain nutrition without pretending that food is a prescription. Every entry should carry evidence, context and uncertainty.</p><div className="health-nav"><span><HeartPulse/> Vitamins & minerals</span><span><Leaf/> Protein & fibre</span><span><ShieldCheck/> Fat quality</span><span><BookOpen/> Evidence</span></div></section><section className="directory-body"><div className="search wide"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search protein, iron, magnesium, B12, fibre…"/></div><div className="nutrient-grid">{filtered.map(n=><article className="nutrient-card" key={n.name}><span className="tag">{n.group}</span><h3>{n.name}</h3><p>{n.role}</p><div><b>Food sources</b><span>{n.sources}</span></div></article>)}</div><div className="health-principles"><h2>The foundation</h2><p>WHO frames healthy diets around adequacy, balance, moderation, diversity and food safety. See the source in the Food Science Lab before treating any general guidance as personal medical advice.</p><p>Crave Plate should therefore avoid simplistic “superfood” rankings. The same ingredient can play different roles depending on portion, preparation, overall dietary pattern and individual context.</p><a className="health-source" href="https://www.who.int/news-room/fact-sheets/detail/healthy-diet" target="_blank" rel="noreferrer">Read WHO healthy-diet guidance <ArrowUpRight size={13}/></a></div></section></main>}
function Science(){return <main className="directory"><section className="directory-hero science-hero"><span className="kicker">FOOD SCIENCE LAB</span><h1>From ingredient → preparation → digestion → absorption → evidence.</h1><p>Interactive boards are designed to distinguish what is known, what is plausible, and what has actually been demonstrated in humans.</p></section><section className="science-grid">{scienceCards.map((c)=><article className="science-card" key={c.title}><div className="science-top"><span className="tag">{c.tag}</span><Dna/></div><h3>{c.title}</h3><strong>{c.claim}</strong><p>{c.detail}</p><a href={c.href} target="_blank" rel="noreferrer">Read source <ArrowUpRight size={14}/></a></article>)}</section><section className="bio-board"><div><span className="kicker">THE BIOAVAILABILITY BOARD</span><h2>What happens after you eat it?</h2><p>For each selected dish, the future engine can show nutrient/compound presence, processing effects, known absorption enhancers or inhibitors, evidence quality, and whether the finding is from food, supplement or isolated-compound research.</p></div><div className="flow"><span>Plate</span><ChevronRight/><span>Digestion</span><ChevronRight/><span>Bioaccessibility</span><ChevronRight/><span>Absorption</span><ChevronRight/><span>Systemic exposure</span><ChevronRight/><span>Evidence</span></div><div className="example"><b>Example: turmeric + pepper</b><p>In a specific 1998 human study, piperine co-administration increased measured curcumin bioavailability by 2000% at the study doses. That does <em>not</em> mean a typical curry delivers a predictable 2000% increase, nor does it establish a disease-treatment effect.</p></div></section><section className="science-note"><CircleHelp/><span>Health content is educational, not diagnosis or individualized medical advice. Medication interactions, pregnancy, allergies, kidney/liver disease and other conditions require qualified clinical guidance.</span></section></main>}
function Collab({partnerType,setPartnerType}){return <main className="directory"><section className="directory-hero collab-hero"><span className="kicker">BUSINESS COLLABORATION WING</span><h1>From a street cart to a global restaurant group.</h1><p>Crave Plate stays open to food businesses of every scale. The collaboration layer can give each partner a digital identity, discovery profile, menu intelligence and a path into future delivery/offer integrations.</p><div className="partner-pills"><span><Store/> Street vendors</span><span><UtensilsCrossed/> Restaurants</span><span><Building2/> Food brands</span><span><Globe2/> Global partners</span></div></section><section className="collab-grid"><div className="collab-panel"><span className="kicker">WHY JOIN</span><h2>Bring the plate. We build the bridge.</h2><ul><li><CheckCircle2/> Get discovered by intent, not only by name.</li><li><CheckCircle2/> Surface your lowkey/local identity.</li><li><CheckCircle2/> Connect menu, offers and delivery reach through permitted integrations.</li><li><CheckCircle2/> Add nutrition facts and ingredient transparency where data exists.</li><li><CheckCircle2/> Participate in Crave Plate editorial, culinary and science projects.</li></ul></div><form className="collab-form" onSubmit={e=>e.preventDefault()}><span className="kicker">OPEN A CONVERSATION</span><h2>Tell us what you are building.</h2><label>Partner type<select value={partnerType} onChange={e=>setPartnerType(e.target.value)}><option>Street vendor</option><option>Restaurant</option><option>Cloud kitchen</option><option>Food brand</option><option>Chef / culinary professional</option><option>Delivery / technology partner</option><option>Nutrition / research organization</option></select></label><label>Business name<input placeholder="Your food place or company"/></label><label>City / region<input placeholder="Hyderabad, India"/></label><label>What can we build together?<textarea placeholder="Menu, delivery, offers, nutrition, discovery, research, technology…"></textarea></label><button className="primary" type="submit">Start collaboration <ArrowUpRight size={16}/></button><small className="form-note">This preview does not transmit data yet. A secure backend submission endpoint will be connected before launch.</small></form></section><section className="collab-principles"><h2>Collaboration principles</h2><div><b>Small businesses matter.</b><span>Street food should not need a giant marketing budget to be discoverable.</span></div><div><b>Transparency matters.</b><span>Partner data should be labelled as partner-provided, verified, estimated or unavailable.</span></div><div><b>People matter.</b><span>Nutrition information should help people understand choices, not shame them.</span></div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
